spring:
  datasource:
    url: jdbc:mysql://sql9.freesqldatabase.com:3306/sql9641179
    username: sql9641179
    password: lZwQUmmBj5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  security:
    user:
      name: jack
      password: shukla

